Cap protobuf < 4.x
tooz doesn't use upper-constraints so we get the newest version of all
dependencies. It seems one of these, etcd3, is incompatible with recent
versions of protobuf.

  Failed to import test module: tooz.tests.drivers.test_etcd3
  Traceback (most recent call last):
    File "/usr/lib/python3.7/unittest/loader.py", line 436, in _find_test_path
      module = self._get_module_from_name(name)
    File "/usr/lib/python3.7/unittest/loader.py", line 377, in _get_module_from_name
      __import__(name)
    File "/home/zuul/src/opendev.org/openstack/tooz/tooz/tests/drivers/test_etcd3.py", line 22, in <module>
      import tooz.drivers.etcd3 as etcd3_driver
    File "/home/zuul/src/opendev.org/openstack/tooz/tooz/drivers/etcd3.py", line 18, in <module>
      import etcd3
    File "/home/zuul/src/opendev.org/openstack/tooz/.tox/py37/lib/python3.7/site-packages/etcd3/__init__.py", line 3, in <module>
      import etcd3.etcdrpc as etcdrpc
    File "/home/zuul/src/opendev.org/openstack/tooz/.tox/py37/lib/python3.7/site-packages/etcd3/etcdrpc/__init__.py", line 1, in <module>
      from .rpc_pb2 import *
    File "/home/zuul/src/opendev.org/openstack/tooz/.tox/py37/lib/python3.7/site-packages/etcd3/etcdrpc/rpc_pb2.py", line 16, in <module>
      from etcd3.etcdrpc import kv_pb2 as kv__pb2
    File "/home/zuul/src/opendev.org/openstack/tooz/.tox/py37/lib/python3.7/site-packages/etcd3/etcdrpc/kv_pb2.py", line 36, in <module>
      type=None),
    File "/home/zuul/src/opendev.org/openstack/tooz/.tox/py37/lib/python3.7/site-packages/google/protobuf/descriptor.py", line 755, in __new__
      _message.Message._CheckCalledFromGeneratedFile()
  TypeError: Descriptors cannot not be created directly.
  If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
  If you cannot immediately regenerate your protos, some other possible workarounds are:
   1. Downgrade the protobuf package to 3.20.x or lower.
   2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).

The etcd3 dependency is only used for the etcd3 driver which was
deprecated in change Iff0cd3b51cfc45ecbddc831c55267e80e9c79cac. The
protobuf dependency is only used for etcd3. We can't outright remove the
etcd3 driver yet as it hasn't been long enough since we deprecated it.
That will happen soon enough though and until then we can simply cap
protobuf to an older version that is compatible with the most recent
etcd3 release.

While we're here, we also sync the lower boundaries in the docs
requirements and add some comments indicating where they come from/what
they're for.

Conflicts:
  requirements.txt

NOTE(stephenfin): Conflicts are due to the absence of change
I14a01f0a9989195e30c3ed0dadec35490f41bd48 ("[ussuri][goal] Drop python
2.7 support and testing"). As the name would suggest, this is an
Ussuri-only thing that we can't backport.

Changes:
  setup.cfg
  test-requirements.txt
  tooz/drivers/mysql.py

NOTE(stephenfin): We also need to set some caps for libraries that
failed to indicate that they had dropped Python 2.7 support using the
proper 'python_requires' setuptools keyword (or equivalent). This
includes 'grpcio' and 'sysv-ipc' (dependencies on the 'etcd3' and 'ipc'
extras in 'setup.cfg', respectively) and 'pifpaf' in
'test-requirements.txt'. We also need to blacklist etcd3gw 0.2.6 to keep
the requirements job happy. This was done elsewhere via change
I22b955419014dd34c63e406c488e0636ffe9013b. Finally, we need to fix a
breakage with PyMySQL 0.10.0. In that version a Connection is no longer
a context manager. We fix this by simply getting a Cursor out of it
(locks don't seem to interact with transactions, at least according to
MariaDB docs). This was done elsewhere via change
I5ea06ebd2b976465ff82f10a74e140f30e9e803f.

Change-Id: I8d6647118be22b0ce55e01b7e5451612ebe30e73
Signed-off-by: Stephen Finucane <stephenfin@redhat.com>
(cherry picked from commit e3de0e634af62e46162eb8d2354416ce4f2ba77c)
(cherry picked from commit 73dbe0e6fc1403cbb121985781d7b6ec996b099a)
(cherry picked from commit 8ca40da4bbe813a76cd48d3e8e54b78d10f25765)
(cherry picked from commit 59da4d8d6aae828c2fd36d1ddf12652c3cee7f7a)